-- CreateTable
CREATE TABLE "Product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "itemName" STRING NOT NULL,
    "price" DECIMAL(15,2) NOT NULL,
    "link" STRING NOT NULL,
    "imageURLs" STRING[],

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Product_itemName_key" ON "Product"("itemName");
